# Build ELOG with GCC 6.5
image: gcc:6.5

pipelines:
  default:
    - step:
        script:
          - apt-get -qq update && apt-get -y -qq install cmake
          - mkdir build; cd build
          - cmake ..
          - make
